_BASE_: "../../../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "../models/FSCE/r50_split1/faster_rcnn_R_101_FPN_all1/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50

  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NAME: "ContrastiveROIHeads"
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256
    # SCORE_THRESH_TEST: 0.0

  ROI_BOX_HEAD:
    CONTRASTIVE_BRANCH:
      TEMPERATURE: 0.2
      LOSS_WEIGHT: 0.2
      DECAY:
        ENABLED: False
        STEPS: [4000, 7000]
        RATE: 0.5
      IOU_THRESHOLD: 0.7  # high credibility proposals provide consistency

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 800
  CROP:
    ENABLED: True

DATASETS:
  TRAIN: ('voc_2007_trainval_all1_5shot',)
  TEST: ('voc_2007_test_all1',)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  GAMMA: 0.5
  STEPS: (5000,7000)
  MAX_ITER: 3000
  CHECKPOINT_PERIOD: 3000
  WARMUP_ITERS: 200

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 3000

#OUTPUT_DIR: "../models/FSCE/faster_DIOR_split1/5shot_CL_IoU"
OUTPUT_DIR: "../../models/FSCE/5shot_ceshi"