_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
  META_ARCHITECTURE: "SiameseRCNN"
  WEIGHTS: "../models/MSOCL4/model_reset_remove.pth"
#  WEIGHTS:  "../models/MSOCL/model_0005999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101

  BACKBONE:
    FREEZE: True
    FREEZE_AT: 5

  PROPOSAL_GENERATOR:
    FREEZE: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000

  ROI_HEADS:
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
    UNFREEZE_FC2: True
    BATCH_SIZE_PER_IMAGE: 256
    IOU_THRESHOLDS: [0.4]

    ROI_BOX_HEAD:
      CONTRASTIVE_BRANCH:
        TEMPERATURE: 0.2
        LOSS_WEIGHT: 0.2
        IOU_THRESHOLD: 0.4
        MLP_FEATURE_DIM: 256

INPUT:
  CROP:
    ENABLED: TRUE
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800

DATASETS:
  TRAIN: ('dior_trainval_all4_1shot',)
  TEST: ('dior_test_all4',)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (3500,)
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 20

TEST:
  EVAL_PERIOD: 3000

OUTPUT_DIR: "checkpoints/voc/1shot_baseline"