_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "../R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 15
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 800
DATASETS:
  TRAIN: ('dior_trainval_base4',)
  TEST: ('dior_test_base4',)
SOLVER:
  GAMMA: 0.1
  STEPS: (20000, 30000)
  MAX_ITER: 40000  # 17.4 epochs
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 3000
  
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 10000
OUTPUT_DIR: "../models/FSCE/faster_DIOR_split3/faster_rcnn_R_101_FPN_base3"
