_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
#  PIXEL_STD: [57.375, 57.120, 58.395]
  WEIGHTS: "../R-101.pkl"
#  WEIGHTS: "../models/FSCE/faster_DIOR_split1/faster_rcnn_R_101_FPN_base1/model_0029999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 15
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 800
DATASETS:
  TRAIN: ('dior_trainval_base1',)
  TEST: ('dior_test_base1',)
SOLVER:
  GAMMA: 0.1
  STEPS: (20000, 30000)
  MAX_ITER: 40000  # 17.4 epochs
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 10000
  
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 5000
OUTPUT_DIR: "../models/MSOCL/faster_DIOR_split1/faster_rcnn_R_101_FPN_base1"
